language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
- stable
- nightly-2018-05-11
- nightly-2018-05-03
- nightly-2018-04-16
script:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force --git https://github.com/xd009642/tarpaulin --branch develop
  - cargo tarpaulin --no-count --skip-clean --verbose
