language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features tls
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch issue_63 
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --skip-clean --no-count
  fi
