language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
script:
  - cargo build 
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch issue_63 
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --skip-clean --no-count
  fi
