language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build 
  - cargo test
after_success: |
    cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch syn_patch 
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --skip-clean --no-count --verbose 
  
