language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build 
  - cargo test
after_success: |
    faktory_path=$PWD
    cd
    git clone https://github.com/xd009642/tarpaulin 
    cd tarpaulin 
    git checkout syn_patch
    cargo run -- tarpaulin -r $faktory_path --no-count --skip-clean --verbose --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
